config/routes.rb
Rails.application.routes.draw do

  scope 'api', defaults: {format: :json} do
    resources :samples, only: [ :show, :index, :create, :update, :destroy]
  end

  root 'application#index'

end

app/models/sample.rb
class Sample
  include Mongoid::Document
  include Mongoid::Paperclip

  field :name, type: String
  field :url, type: String
  field :audiofile, type: String
  field :category, type: String

  has_mongoid_attached_file :afile,
  	:storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")

  validates_attachment_content_type :afile, :content_type => /.*/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def index
  end
  
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController

  def index
    samples = Sample.all
    render json: samples, status: 200
  end

  def show
    sample = Sample.find(params[:id])
    render json: sample, status: 201
  end


  def create
    sample = Sample.create(sample_params)
    render json: sample, status: 201
  end

  def update
    sample = Sample.find(params[:id])
    sample.update_attributes(sample_params)
    render nothing: true, status: 204
  end

  def destroy
    sample = Sample.find(params[:id])
    sample.destroy
    render nothing: true, status: 204
  end

  private

  def sample_params
    params.require(:sample).permit(:name, :url, :audiofile, :category, :afile)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/application/index.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

<h4>INDEX PARTIAL</h4>

<div ui-view></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Angular Samplr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- Base is the root from base tag, using $locationProvider, requireBase True -->

  <base href="/">
</head>
<body ng-app="myApp" manifest="assets/javascripts/angular/app.js">

  <a ui-sref="home">HOME</a>

<%= yield %>

</body>
</html>

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Listing samples</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= link_to 'Show', sample %></td>
        <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>